### ISSUE TITLE
Not an issue :) 

### ISSUE THREAD

**Issue by N4m3lessOne** [digitaljohn/comfyui-propost#19]
Hey, just wanted to say that the nodes are really useful and produce visually pleasing results, but is there any way they could run faster? Processing 384 frames long 1344x768 video clip using radial blur, vignette and film grain takes 20 minutes on rtx 4090

**Comment by digitaljohn** [comment]
The goal of this package was to be high quality and supporting video was actually just a nice surprise. There are a few points:

1. Noise is cached, so subsequent reruns with the same fixed seed should help a bit.
2. Steps on radial blur and depth map blue is quite heavy. For each step a full image blur needs to be performed. < 4 steps should be acceptable in most scenarios.
