### ISSUE TITLE
getting issue when running film grain 

### ISSUE THREAD

**Issue by alenknight** [digitaljohn/comfyui-propost#24]
when running the film grain node, getting this error 
![Screenshot 2024-06-18 at 12 19 37 PM](https://github.com/digitaljohn/comfyui-propost/assets/22153900/c4049ff8-b76d-449f-a417-675eff5aa7ed)

**Comment by Aljnk** [comment]
same problem

**Comment by Aljnk** [comment]
you problem here - ComfyUI_MaraScott_Nodes
I delete it and use original - work :)
