### ISSUE TITLE
Broken with ComfyUI: 2856[ab885b](2024-11-23)

### ISSUE THREAD

**Issue by Krishicall** [digitaljohn/comfyui-propost#31]
Broken with comfy version
ComfyUI: 2856[ab885b](2024-11-23)

<img width="470" alt="image" src="https://github.com/user-attachments/assets/549c0fe2-0661-442c-97e3-625773768839">

**Comment by digitaljohn** [comment]
Could you please provide steps to reproduce? With a fresh install of ComfyUI `ComfyUI v0.3.9-21-g73e0498` I experience no issues.
